### ISSUE TITLE
Kalkulaatori tehniline kirjeldus

### ISSUE THREAD

**Issue by rrrrando** [kuressaareametikool/emale#3]
Siia kirjutab Siivi...

**Comment by Siivi** [comment]
2014 (aasta andmed statistikametist) oli alampalk 355. Hetkel 2020 on alampalk 584. Indeksiga 584/355=1.645 korrutada läbi palgad, mis on saadud 2014 aasta statistikast (tasu võib olla suurem, aga ei saa olla väiksem). 2018. aasta andmed avaldatakse hiljemalt 30.06.2020. Siis oleks indeks 584/500=1.168.   
Öösel (22.00 kuni 6.00) töötamise eest peab tööandja maksma töötajale 1,25-kordset töötasu.
Kui töötaja tööaeg langeb riigipühale, peab tööandja maksma töö eest 2-kordset töötasu.
Ületundide eest peab tööandja maksma 1,5 kordset töötasu. 
Põhimõtteliselt baastasu arvestatakse üks kord läbi vastavate koefitsentidega ja liidetakse - jämedalt öeldes tasutatakse 2,5-kordselt. Sellest tulenevalt on lisavõimalus arvestada lisatööd/öötööd korrutades läbi 2.

**Comment by rrrrando** [comment]
Kas oleks ka mingi hea lahendus, kuidas seda saaks mingiks keskmiseks numbriks arvutada, muidu läheb see tabel jube kirjuks ja keeruliseks. Ütleme, et inimene täidab ära tunnid päeva kohta ja siis on meil mingi valem, mis võtab arvesse keskmise nädalavahetuse ja ületöö tunnid koos tavatundidega

**Comment by Siivi** [comment]
Esialgu läbi korrutada 1.645 mida tuleb käsitsi muuta kui statistikaamet uuendab oma andmeid ja muidugi kui alampalk tõuseb tuleks ka arvutada uus indeks. 
Lisada võimalus näiteks checkboxina mis korrutab läbi 2 ehk siis topelt(öötöö, ületund, riigipüha), et jätta ära juuksekarva lõhki ajamine.

**Comment by rrrrando** [comment]
Ma ei tea kas sa hommikul kuulsid aga esialgu leppisime kokku, et kahega korrutamist ei pane. Hiljem saaks selle lisada kui vaja
